// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKFumd2_P-UpNDbkadpJ7CD40t8_V_xY',
    appId: '1:979895626799:web:83c4e6761e742841c82ada',
    messagingSenderId: '979895626799',
    projectId: 'hamarakisan-5a45b',
    authDomain: 'hamarakisan-5a45b.firebaseapp.com',
    storageBucket: 'hamarakisan-5a45b.firebasestorage.app',
    measurementId: 'G-NLNVYTNKB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Dp8FA1nDfFlm1GB0kiAuC0jwAHOu0aA',
    appId: '1:979895626799:android:9167dc13d24cc442c82ada',
    messagingSenderId: '979895626799',
    projectId: 'hamarakisan-5a45b',
    storageBucket: 'hamarakisan-5a45b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDywRcgY3oJMEL7SWtKjWSJSuIPcFJJoVY',
    appId: '1:979895626799:ios:2c6b20475f218126c82ada',
    messagingSenderId: '979895626799',
    projectId: 'hamarakisan-5a45b',
    storageBucket: 'hamarakisan-5a45b.firebasestorage.app',
    androidClientId: '979895626799-raip5ifqa168sefj9bdndq6pn20l867a.apps.googleusercontent.com',
    iosClientId: '979895626799-vge3o4npnsd1gcbct4jn9grggqge51lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamarakisanFront',
  );
}
