Map stateDistrictMap = {
  "Andaman and Nicobar": [
    "Nicobar",
    "North and Middle Andaman",
    "South Andaman",
  ],

  "Andhra Pradesh": [
    "Anantapur",
    "Chittor",
    "Cuddapah",
    "East Godavari",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Vijayanagaram",
    "Visakhapatnam",
    "West Godavari",
  ],

  "Arunachal Pradesh": [
    "Changlang",
    "East Kameng",
    "East Siang",
    "Kurung Kummey",
    "Lohit",
    "Lower Dibang Valley",
    "Lower Subansiri",
    "Papum Pore",
    "Tawang",
    "Tirap",
    "Upper Siang",
    "Upper Subansiri",
    "West Kameng",
    "West Siang",
  ],

  "Assam": [
    "Barpeta",
    "BONGAIGAON",
    "Cachar",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Jorhat",
    "Kamrup",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Mangaldoi",
    "MORIGAON",
    "Nagaon",
    "Nalbari",
    "North Cachar Hills",
    "Sibsagar",
    "Sonitpur",
    "Tinsukia",
  ],

  "Bihar": [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Buxar",
    "Chhapra",
    "Darbhanga",
    "East Champaran/ Motihari",
    "Gaya",
    "Gopalgang",
    "Jamui",
    "Jehanabad",
    "Kaimur/Bhabhua",
    "Kaithar",
    "Khagaria",
    "Kishanganj",
    "Luckeesarai",
    "Madhepura",
    "Madhubani",
    "Munghair",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnea",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    "Saran",
    "Sheikhpura",
    "Sheohar",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali",
    "West Chambaran",
  ],

  "Chandigarh": ["Chandigarh"],

  "Chattisgarh": [
    "Balod",
    "Balodabazar",
    "Balrampur",
    "Bastar",
    "Bemetara",
    "Bijapur",
    "Bilaspur",
    "Dantewada",
    "Dhamtari",
    "Durg",
    "Gariyaband",
    "Jagdalpur",
    "Janjgir",
    "Jashpur",
    "Kabirdham",
    "Kanker",
    "Kawardha",
    "Kondagaon",
    "Korba",
    "Koria",
    "Mahasamund",
    "Mungeli",
    "Narayanpur",
    "North Bastar",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
    "Sukma",
    "Surajpur",
    "Surguja",
  ],

  "Dadra and Nagar Haveli": ["Dadra & Nagar Haveli", "Silvassa"],

  "Daman and Diu": ["Daman", "Diu"],

  "Goa": ["North Goa", "South Goa"],

  "Gujarat": [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskanth",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhota Udaipur",
    "Dahod",
    "Dang",
    "Devbhumi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagarh",
    "Kachchh",
    "Kheda",
    "Mahisagar",
    "Mehsana",
    "Morbi",
    "Narmada",
    "Navsari",
    "Panchmahals",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha",
    "Surat",
    "Surendranagar",
    "Tapi",
    "The Dangs",
    "Vadodara(Baroda)",
    "Valsad",
  ],

  "Haryana": [
    "Ambala",
    "Bhiwani",
    "Faridabad",
    "Fatehabad",
    "Gurgaon",
    "Hissar",
    "Jhajar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh-Narnaul",
    "Mewat",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamuna Nagar",
  ],

  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kangra (at Dharmashala)",
    "Kinnaur (at Kalpa)",
    "Kullu",
    "Lahul & Spiti",
    "Mandi",
    "Shimla",
    "Sirmore",
    "Solan",
    "Una",
  ],

  "Jammu and Kashmir": [
    "Anantnag",
    "Badgam",
    "Bandipora",
    "Baramulla",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kargil",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Leh",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],

  "Jharkhand": [
    "Bokaro",
    "Chatra",
    "Deogarh",
    "Dhanbad",
    "Dumka",
    "East Singhbhum",
    "Garhwa",
    "Giridih",
    "Godda",
    "Gumla",
    "Hazaribagh",
    "Jamtara",
    "Koderma",
    "Latehar",
    "Lohardaga",
    "Pakur",
    "Palamu",
    "Ranchi",
    "Sahebgang",
    "Saraikela(Kharsanwa)",
    "Simdega",
    "West Singbhum",
  ],

  "Karnataka": [
    "Bagalkot",
    "Bangalore",
    "Belgaum",
    "Bellary",
    "Bidar",
    "Bijapur",
    "Chamrajnagar",
    "Chikmagalur",
    "Chitradurga",
    "Davangere",
    "Dharwad",
    "Gadag",
    "Hassan",
    "Haveri",
    "Kalburgi",
    "Karwar(Uttar Kannad)",
    "Kolar",
    "Koppal",
    "Madikeri(Kodagu)",
    "Mandya",
    "Mangalore(Dakshin Kannad)",
    "Mysore",
    "Raichur",
    "Ramanagar",
    "Shimoga",
    "Tumkur",
    "Udupi",
    "Yadgiri",
  ],

  "Kerala": [
    "Alappuzha",
    "Alleppey",
    "Calicut",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasargod",
    "Kollam",
    "Kottayam",
    "Kozhikode(Calicut)",
    "Malappuram",
    "Palakad",
    "Pathanamthitta",
    "Thirssur",
    "Thiruvananthapuram",
    "Wayanad",
  ],

  "Lakshadweep": ["Kavaratti"],

  "Madhya Pradesh": [
    "Agar Malwa",
    "Alirajpur",
    "Anupur",
    "Ashoknagar",
    "Badwani",
    "Balaghat",
    "Betul",
    "Bhind",
    "Bhopal",
    "Burhanpur",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "Mandla",
    "Mandsaur",
    "Morena",
    "Narsinghpur",
    "Neemuch",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shajapur",
    "Shehdol",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Singroli",
    "Tikamgarh",
    "Ujjain",
    "Umariya",
    "Vidisha",
  ],

  "Maharashtra": [
    "Ahmednagar",
    "Akola",
    "Amarawati",
    "Bandra(E)",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Chandrapur",
    "Chattrapati Sambhajinagar",
    "Dharashiv(Usmanabad)",
    "Dhule",
    "Gadchiroli",
    "Gondiya",
    "Hingoli",
    "Jalana",
    "Jalgaon",
    "Kolhapur",
    "Latur",
    "Mumbai",
    "Murum",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sholapur",
    "Sindhudurg",
    "Thane",
    "Vashim",
    "Wardha",
    "Yavatmal",
  ],

  "Manipur": [
    "Bishnupur",
    "Chandel",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Kakching",
    "Senapati",
    "Tamenglong",
    "Tengnoupal",
    "Thoubal",
    "Ukhrul",
  ],

  "Meghalaya": [
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "Nongpoh (R-Bhoi)",
    "North Garo Hills",
    "South Garo Hills",
    "South West Garo Hills",
    "South West Khasi Hills",
    "West Garo Hills",
    "West Jaintia Hills",
    "West Khasi Hills",
  ],

  "Mizoram": ["Aizawl", "Kolasib", "Lungli", "Mamit", "Saiha"],
  "Nagaland": [
    "Dimapur",
    "Kohima",
    "Mokokchung",
    "Mon",
    "Phek",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Kiphire",
    "Longleng",
    "Peren",
    "Tuensang",
  ],
  "NCT of Delhi": ["Delhi"],
  "Odisha": [
    "Angul",
    "Balasore",
    "Bargarh",
    "Berhampur",
    "Bhadrak",
    "Bhubaneswar",
    "Bolangir",
    "Boudh",
    "Cuttack",
    "Deogarh",
    "Dhenkanal",
    "Gajapati",
    "Ganjam",
    "Jagatsinghpur",
    "Jajpur",
    "Jharsuguda",
    "Kalahandi",
    "Kandhamal",
    "Kendrapara",
    "Keonjhar",
    "Khurda",
    "Koraput",
    "Malkangiri",
    "Mayurbhanja",
    "Nayagarh",
    "Nowarangpur",
    "Nuapada",
    "Puri",
    "Rayagada",
    "Rourkela",
    "Sambalpur",
    "Sonepur",
    "Sundergarh",
  ],

  "Pondicherry": ["Karaikal", "Mahe", "Pondicherry", "Yanam"],
  "Punjab": [
    "Amritsar",
    "Barnala",
    "Bhatinda",
    "Faridkot",
    "Fatehgarh",
    "Fazilka",
    "Ferozpur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "kapurthala",
    "Ludhiana",
    "Mansa",
    "Moga",
    "Mohali",
    "Muktsar",
    "Nawanshahr",
    "Pathankot",
    "Patiala",
    "Ropar (Rupnagar)",
    "Sangrur",
    "Tarntaran",
  ],
  "Rajasthan": [
    "Jhunjhunu",
    "Ajmer",
    "Alwar",
    "Anupgarh",
    "Balotra",
    "Banswara",
    "Baran",
    "Barmer",
    "Beawar",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Deedwana Kuchaman",
    "Deeg",
    "Dholpur",
    "Dudu",
    "Dungarpur",
    "Ganganagar",
    "Gangapur City",
    "Hanumangarh",
    "Jaipur",
    "Jaipur Rural",
    "Jaisalmer",
    "Jalore",
    "Jhalawar",
    "Jodhpur",
    "Jodhpur Rural",
    "Karauli",
    "Kekri",
    "Khairthal Tijara",
    "Kota",
    "Kotputli- Behror",
    "Nagaur",
    "Neem Ka Thana",
    "Pali",
    "Phalodi",
    "Pratapgarh",
    "Rajsamand",
    "Sanchore",
    "Shahpura",
    "Sikar",
    "Sirohi",
    "Swai Madhopur",
    "Tonk",
    "Udaipur",
  ],
  "Sikkim": [
    "East",
    "North Sikkim (Mangan)",
    "South Sikkim (Namchi)",
    "West Sikkim (Gyalsing)",
  ],
  "Tamil Nadu": [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakuruchi",
    "Kancheepuram",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Nagercoil (Kannyiakumari)",
    "Namakkal",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "The Nilgiris",
    "Theni",
    "Thiruchirappalli",
    "Thirunelveli",
    "Thirupathur",
    "Thirupur",
    "Thiruvannamalai",
    "Thiruvarur",
    "Thiruvellore",
    "Tuticorin",
    "Vellore",
    "Villupuram",
    "Virudhunagar",
  ],
  "Telangana": [
    "Adilabad",
    "Hyderabad",
    "Jagityal",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Medak",
    "Nalgonda",
    "Nizamabad",
    "Ranga Reddy",
    "Siddipet",
    "Warangal",
  ],
  "Tripura": [
    "Dhalai",
    "Gomati",
    "Khowai",
    "North Tripura",
    "Sepahijala",
    "South District",
    "Unokoti",
    "West District",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkarnagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Badaun",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi(Sant Ravi Nagar)",
    "Bijnor",
    "Bulandshahar",
    "Chandauli",
    "Chitrakut",
    "Deoria",
    "Etah",
    "Etawah",
    "Farukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Budh Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hardoi",
    "Hathras",
    "Jalaun (Orai)",
    "Jaunpur",
    "Jhansi",
    "Kannuj",
    "Kanpur",
    "Kanpur Dehat",
    "Kasganj",
    "Kaushambi",
    "Khiri (Lakhimpur)",
    "Kushinagar",
    "Lakhimpur",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau(Maunathbhanjan)",
    "Meerut",
    "Mirzapur",
    "Muzaffarnagar",
    "Oraya",
    "Pillibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebarelli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharth Nagar",
    "Sitapur",
    "Sonbhadra",
    "Unnao",
    "Varanasi",
  ],
  "Uttrakhand": [
    "Almora",
    "Bageshwar",
    "Chamoli (Gopeshwar)",
    "Champawat",
    "Dehradoon",
    "Garhwal (Pauri)",
    "Haldwani",
    "Haridwar",
    "Nanital",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "UdhamSinghNagar",
    "Uttarkashi",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Burdwan",
    "Coochbehar",
    "Dakshin Dinajpur",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Medinipur(E)",
    "Medinipur(W)",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Bardhaman",
    "Purba Bardhaman",
    "Puruliya",
    "Sounth 24 Parganas",
    "Uttar Dinajpur",
  ],
};


List<String> commodity_list = [
    "Absinthe",
    "Ajwan",
    "Alasande Gram",
    "Almond(Badam)",
    "Alsandikai",
    "Amaranthus",
    "Ambada Seed",
    "Ambady/Mesta",
    "Amla(Nelli Kai)",
    "Amphophalus",
    "Amranthas Red",
    "Antawala",
    "Anthorium",
    "Apple",
    "Apricot(Jardalu/Khumani)",
    "Arecanut(Betelnut/Supari)",
    "Arhar (Tur/Red Gram)(Whole)",
    "Arhar Dal(Tur Dal)",
    "Asalia",
    "Asgand",
    "Ashgourd",
    "Ashoka",
    "Ashwagandha",
    "Asparagus",
    "Astera",
    "Atis",
    "Avare Dal",
    "Bael",
    "Bajji chilli",
    "Bajra(Pearl Millet/Cumbu)",
    "Balekai",
    "balsam",
    "Bamboo",
    "Banana",
    "Banana - Green",
    "Banana flower",
    "Banana Leaf",
    "Banana stem",
    "Barley (Jau)",
    "basil",
    "Bay leaf (Tejpatta)",
    "Beans",
    "Beaten Rice",
    "Beetroot",
    "Behada",
    "Bengal Gram Dal (Chana Dal)",
    "Bengal Gram(Gram)(Whole)",
    "Ber(Zizyphus/Borehannu)",
    "Betal Leaves",
    "Betelnuts",
    "Bhindi(Ladies Finger)",
    "Bhui Amlaya",
    "Big Gram",
    "Binoula",
    "Bitter gourd",
    "Black Gram (Urd Beans)(Whole)",
    "Black Gram Dal (Urd Dal)",
    "Black pepper",
    "BOP",
    "Borehannu",
    "Bottle gourd",
    "Brahmi",
    "Bran",
    "Bread Fruit",
    "Brinjal",
    "Brocoli",
    "Broken Rice",
    "Broomstick(Flower Broom)",
    "Bull",
    "Bullar",
    "Bunch Beans",
    "Butter",
    "buttery",
    "Cabbage",
    "Calendula",
    "Calf",
    "Camel Hair",
    "Cane",
    "Capsicum",
    "Cardamoms",
    "Carnation",
    "Carrot",
    "Cashew Kernnel",
    "Cashewnuts",
    "Castor Oil",
    "Castor Seed",
    "Cauliflower",
    "Chakotha",
    "Chandrashoor",
    "Chapparad Avare",
    "Chennangi (Whole)",
    "Chennangi Dal",
    "Cherry",
    "Chikoos(Sapota)",
    "Chili Red",
    "Chilly Capsicum",
    "Chironji",
    "Chow Chow",
    "Chrysanthemum",
    "Chrysanthemum(Loose)",
    "Cinamon(Dalchini)",
    "cineraria",
    "Clarkia",
    "Cloves",
    "Cluster beans",
    "Coca",
    "Cock",
    "Cocoa",
    "Coconut",
    "Coconut Oil",
    "Coconut Seed",
    "Coffee",
    "Colacasia",
    "Copra",
    "Coriander(Leaves)",
    "Corriander seed",
    "Cossandra",
    "Cotton",
    "Cotton Seed",
    "Cow",
    "Cowpea (Lobia/Karamani)",
    "Cowpea(Veg)",
    "Cucumbar(Kheera)",
    "Cummin Seed(Jeera)",
    "Curry Leaf",
    "Custard Apple (Sharifa)",
    "Daila(Chandni)",
    "Dal (Avare)",
    "Dalda",
    "Delha",
    "Dhaincha",
    "dhawai flowers",
    "dianthus",
    "Double Beans",
    "Dragon fruit",
    "dried mango",
    "Drumstick",
    "Dry Chillies",
    "Dry Fodder",
    "Dry Grapes",
    "Duck",
    "Duster Beans",
    "Egg",
    "Egypian Clover(Barseem)",
    "Elephant Yam (Suran)",
    "Field Pea",
    "Fig(Anjura/Anjeer)",
    "Firewood",
    "Fish",
    "Flax seeds",
    "Flower Broom",
    "Foxtail Millet(Navane)",
    "French Beans (Frasbean)",
    "Galgal(Lemon)",
    "Gamphrena",
    "Garlic",
    "Ghee",
    "Giloy",
    "Gingelly Oil",
    "Ginger(Dry)",
    "Ginger(Green)",
    "Gladiolus Bulb",
    "Gladiolus Cut Flower",
    "Glardia",
    "Goat",
    "Goat Hair",
    "golden rod",
    "Gond",
    "Goose berry (Nellikkai)",
    "Gram Raw(Chholia)",
    "Gramflour",
    "Grapes",
    "Green Avare (W)",
    "Green Chilli",
    "Green Fodder",
    "Green Gram (Moong)(Whole)",
    "Green Gram Dal (Moong Dal)",
    "Green Peas",
    "Ground Nut Oil",
    "Ground Nut Seed",
    "Groundnut",
    "Groundnut (Split)",
    "Groundnut pods (raw)",
    "Guar",
    "Guar Seed(Cluster Beans Seed)",
    "Guava",
    "Gudmar",
    "Guggal",
    "gulli",
    "Gur(Jaggery)",
    "Gurellu",
    "gypsophila",
    "Haralekai",
    "Harrah",
    "He Buffalo",
    "Heliconia species",
    "Hen",
    "Hippe Seed",
    "Honey",
    "Honge seed",
    "Hybrid Cumbu",
    "hydrangea",
    "Indian Beans (Seam)",
    "Indian Colza(Sarson)",
    "Irish",
    "Isabgul (Psyllium)",
    "Jack Fruit",
    "Jaee",
    "Jaffri",
    "Jaggery",
    "Jamamkhan",
    "Jamun(Narale Hannu)",
    "Jarbara",
    "Jasmine",
    "Javi",
    "Jowar(Sorghum)",
    "Jute",
    "Jute Seed",
    "Kabuli Chana(Chickpeas-White)",
    "Kacholam",
    "Kakada",
    "kakatan",
    "Kalihari",
    "Kalmegh",
    "Kankambra",
    "Karamani",
    "karanja seeds",
    "Karbuja(Musk Melon)",
    "Kartali (Kantola)",
    "Kevda",
    "Kharif Mash",
    "Khirni",
    "Khoya",
    "Kinnow",
    "Knool Khol",
    "Kodo Millet(Varagu)",
    "kokum",
    "Kooth",
    "Kuchur",
    "Kulthi(Horse Gram)",
    "Kutki",
    "kutki",
    "Ladies Finger",
    "Laha",
    "Lak(Teora)",
    "Leafy Vegetable",
    "Lemon",
    "Lentil (Masur)(Whole)",
    "Lilly",
    "Lime",
    "Limonia (status)",
    "Linseed",
    "Lint",
    "liquor turmeric",
    "Litchi",
    "Little gourd (Kundru)",
    "Long Melon(Kakri)",
    "Lotus",
    "Lotus Sticks",
    "Lukad",
    "Lupine",
    "Ma.Inji",
    "Mace",
    "macoy",
    "Mahedi",
    "Mahua",
    "Mahua Seed(Hippe seed)",
    "Maida Atta",
    "Maize",
    "Mango",
    "Mango (Raw-Ripe)",
    "mango powder",
    "Maragensu",
    "Marasebu",
    "Marget",
    "Marigold(Calcutta)",
    "Marigold(loose)",
    "Marikozhunthu",
    "Mash",
    "Mashrooms",
    "Masur Dal",
    "Mataki",
    "Methi Seeds",
    "Methi(Leaves)",
    "Millets",
    "Mint(Pudina)",
    "Moath Dal",
    "Moath Dal",
    "Mousambi(Sweet Lime)",
    "Muesli",
    "Muleti",
    "Muskmelon Seeds",
    "Mustard",
    "Mustard Oil",
    "Myrobolan(Harad)",
    "Nargasi",
    "Nearle Hannu",
    "Neem Seed",
    "Nelli Kai",
    "Nerium",
    "nigella seeds",
    "nigella seeds",
    "Niger Seed (Ramtil)",
    "Nutmeg",
    "Onion",
    "Onion Green",
    "Orange",
    "Orchid",
    "Other green and fresh vegetables",
    "Other Pulses",
    "Ox",
    "Paddy(Dhan)(Basmati)",
    "Paddy(Dhan)(Common)",
    "Palash flowers",
    "Papaya",
    "Papaya (Raw)",
    "Patti Calcutta",
    "Peach",
    "Pear(Marasebu)",
    "Peas cod",
    "Peas Wet",
    "Peas(Dry)",
    "Pegeon Pea (Arhar Fali)",
    "Pepper garbled",
    "Pepper ungarbled",
    "Perandai",
    "Persimon(Japani Fal)",
    "Pigs",
    "Pineapple",
    "pippali",
    "Plum",
    "Pointed gourd (Parval)",
    "Polherb",
    "Pomegranate",
    "Poppy capsules",
    "poppy seeds",
    "Potato",
    "Pumpkin",
    "Pundi",
    "Pundi Seed",
    "Pupadia",
    "Raddish",
    "Ragi (Finger Millet)",
    "Raibel",
    "Rajgir",
    "Rala",
    "Ram",
    "Ramphal",
    "Rat Tail Radish (Mogari)",
    "Ratanjot",
    "Raya",
    "Rayee",
    "Red Cabbage",
    "Red Gram",
    "Resinwood",
    "Riccbcan",
    "Rice",
    "Ridgeguard(Tori)",
    "Rose(Local)",
    "Rose(Loose))",
    "Rose(Tata)",
    "Round gourd",
    "Rubber",
    "Sabu Dan",
    "Safflower",
    "Saffron",
    "Sajje",
    "salvia",
    "Same/Savi",
    "sanay",
    "Sandalwood",
    "Sarasum",
    "Season Leaves",
    "Seegu",
    "Seemebadnekai",
    "Seetapal",
    "Sesamum(Sesame,Gingelly,Til)",
    "sevanti",
    "She Buffalo",
    "She Goat",
    "Sheep",
    "Siddota",
    "Siru Kizhagu",
    "Skin And Hide",
    "Snakeguard",
    "Soanf",
    "Soapnut(Antawala/Retha)",
    "Soha",
    "Soji",
    "Sompu",
    "Soyabean",
    "spikenard",
    "Spinach",
    "Sponge gourd",
    "Squash(Chappal Kadoo)",
    "stevia",
    "stone pulverizer",
    "Sugar",
    "Sugarcane",
    "Sundaikai",
    "Sunflower",
    "Sunflower Seed",
    "Sunhemp",
    "Suram",
    "Surat Beans (Papadi)",
    "Suva (Dill Seed)",
    "Suvarna Gadde",
    "Sweet Potato",
    "Sweet Pumpkin",
    "Sweet Sultan",
    "sweet william",
    "T.V. Cumbu",
    "Tamarind Fruit",
    "Tamarind Seed",
    "Tapioca",
    "Tinda",
    "Tobacco",
    "Tomato",
    "Torchwood",
    "Toria",
    "Tube Flower",
    "Tube Rose(Double)",
    "Tube Rose(Loose)",
    "Tube Rose(Single)",
    "Tulasi",
    "tulip",
    "Turmeric",
    "Turmeric (raw)",
    "Turnip",
    "vadang",
    "Vatsanabha",
    "Walnut",
    "Water Apple",
    "Water chestnut",
    "Water Melon",
    "Wax",
    "Wheat",
    "Wheat Atta",
    "White Muesli",
    "White Peas",
    "White Pumpkin",
    "Wild lemon",
    "Wood",
    "Wood Apple",
    "Wool",
    "Yam",
    "Yam (Ratalu)",
];